### PR TITLE
Namespaces correction in app/ directory to respect PRS-4

### PR DESCRIPTION
**Pull request by percymamedy**
All namespaces of classes in the app/ directory should be capitalize,
hence app should be used as App instead.

### CODE REVIEW

**Comment by gocanto** [comment]
I do not have any idea why I did not receive the notification

**Comment by percymamedy** [comment]
No problem, I have detected some more corrections.. still working on those... I also have some ideas and suggestions....

**Comment by gocanto** [comment]
Do you use slack, skype or anything related to? I would to add u by there so we can comunicate better

**Comment by percymamedy** [comment]
Sent u my info on Facebook..:)

**Pull request merged**
